// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/barrier-transmission.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/physics.ts
var clamp = (v, lo = 0, hi = 1) => Math.min(hi, Math.max(lo, v));
function barrierTransmission(E_eV, V_eV, a_nm) {
  const K0 = 5.1231;
  if (Math.abs(E_eV - V_eV) < 1e-6) {
    const denom2 = 1 + K0 * K0 * V_eV * a_nm * a_nm / 4;
    return { T: 1 / denom2, kappa_a: 0, regime: "resonant" };
  }
  if (E_eV < V_eV) {
    const kappa = K0 * Math.sqrt(V_eV - E_eV);
    const ka2 = kappa * a_nm;
    const sh = Math.sinh(ka2);
    const denom2 = 1 + V_eV * V_eV * sh * sh / (4 * E_eV * (V_eV - E_eV));
    return { T: 1 / denom2, kappa_a: ka2, regime: "tunneling" };
  }
  const k = K0 * Math.sqrt(E_eV - V_eV);
  const ka = k * a_nm;
  const s = Math.sin(ka);
  const denom = 1 + V_eV * V_eV * s * s / (4 * E_eV * (E_eV - V_eV));
  return { T: 1 / denom, kappa_a: ka, regime: "oscillatory" };
}
function doubleSlitIntensity(y_mm, d_um, lambda_nm, L_mm) {
  const theta = Math.atan2(y_mm, L_mm);
  const arg = Math.PI * (d_um * 1e3) * Math.sin(theta) / lambda_nm;
  return Math.cos(arg) ** 2;
}
function bornProbabilities(theta) {
  const p0 = Math.cos(theta / 2) ** 2;
  return { p0, p1: 1 - p0 };
}
function teleportationFidelity(bellPurity, decoherence) {
  return clamp(bellPurity * (1 - decoherence * 0.5) + 0.25 * (1 - bellPurity));
}
function wernerConcurrence(purity) {
  return Math.max(0, (3 * purity - 1) / 2);
}

// src/lib/mcp/tools/barrier-transmission.ts
var barrier_transmission_default = defineTool({
  name: "barrier_transmission",
  title: "1D barrier transmission",
  description: "Compute the transmission coefficient T for a non-relativistic electron crossing a 1D rectangular potential barrier. Handles tunneling (E<V), resonant (E=V), and oscillatory (E>V) regimes.",
  inputSchema: {
    energy_eV: z.number().positive().describe("Particle energy E in eV."),
    barrier_eV: z.number().positive().describe("Barrier height V in eV."),
    width_nm: z.number().positive().describe("Barrier width a in nm.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ energy_eV, barrier_eV, width_nm }) => {
    const { T, kappa_a, regime } = barrierTransmission(energy_eV, barrier_eV, width_nm);
    const text = `T = ${T.toExponential(4)} (regime: ${regime}, \u03BAa = ${kappa_a.toFixed(4)})`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { transmission: T, reflection: 1 - T, kappa_a, regime }
    };
  }
});

// src/lib/mcp/tools/double-slit-intensity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var double_slit_intensity_default = defineTool2({
  name: "double_slit_intensity",
  title: "Double-slit intensity",
  description: "Fraunhofer double-slit intensity (arbitrary units, normalized to 1) at screen position y for slit separation d, wavelength \u03BB, and screen distance L.",
  inputSchema: {
    y_mm: z2.number().describe("Screen position y in millimeters (may be negative)."),
    slit_separation_um: z2.number().positive().describe("Slit separation d in micrometers."),
    wavelength_nm: z2.number().positive().describe("Wavelength \u03BB in nanometers."),
    screen_distance_mm: z2.number().positive().describe("Slit-to-screen distance L in millimeters.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ y_mm, slit_separation_um, wavelength_nm, screen_distance_mm }) => {
    const I = doubleSlitIntensity(y_mm, slit_separation_um, wavelength_nm, screen_distance_mm);
    return {
      content: [{ type: "text", text: `I/I\u2080 = ${I.toFixed(6)} at y = ${y_mm} mm` }],
      structuredContent: { intensity: I }
    };
  }
});

// src/lib/mcp/tools/born-probabilities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var born_probabilities_default = defineTool3({
  name: "born_probabilities",
  title: "Born-rule probabilities",
  description: "Compute measurement probabilities p(0) and p(1) for a single-qubit state |\u03C8\u27E9 = cos(\u03B8/2)|0\u27E9 + e^{i\u03C6} sin(\u03B8/2)|1\u27E9 in the computational basis.",
  inputSchema: {
    theta_rad: z3.number().describe("Polar angle \u03B8 on the Bloch sphere, in radians.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ theta_rad }) => {
    const { p0, p1 } = bornProbabilities(theta_rad);
    return {
      content: [{ type: "text", text: `p(0) = ${p0.toFixed(6)}, p(1) = ${p1.toFixed(6)}` }],
      structuredContent: { p0, p1 }
    };
  }
});

// src/lib/mcp/tools/teleportation-fidelity.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var teleportation_fidelity_default = defineTool4({
  name: "teleportation_fidelity",
  title: "Teleportation fidelity",
  description: "Estimate the average teleportation fidelity F using a Werner Bell-pair of purity p degraded by a decoherence factor d \u2208 [0, 1]. Also returns the Werner concurrence of the shared pair.",
  inputSchema: {
    bell_purity: z4.number().min(0).max(1).describe("Bell-pair Werner purity p \u2208 [0, 1]."),
    decoherence: z4.number().min(0).max(1).describe("Decoherence factor d \u2208 [0, 1] (0 = ideal).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bell_purity, decoherence }) => {
    const F = teleportationFidelity(bell_purity, decoherence);
    const C = wernerConcurrence(bell_purity);
    return {
      content: [{ type: "text", text: `F = ${F.toFixed(6)}, concurrence C = ${C.toFixed(6)}` }],
      structuredContent: { fidelity: F, concurrence: C, entangled: C > 0 }
    };
  }
});

// src/lib/mcp/tools/pauli-correction.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var OPERATORS = {
  "00": { op: "I", description: "Identity \u2014 no correction needed" },
  "01": { op: "X", description: "Bit flip on Bob's qubit" },
  "10": { op: "Z", description: "Phase flip on Bob's qubit" },
  "11": { op: "X\xB7Z", description: "Bit flip followed by phase flip" }
};
var pauli_correction_default = defineTool5({
  name: "pauli_correction",
  title: "Teleportation Pauli correction",
  description: "Given Alice's two classical measurement bits (m1, m2) from a Bell-basis measurement in the standard quantum teleportation protocol, return the Pauli correction Bob must apply to recover |\u03C8\u27E9.",
  inputSchema: {
    m1: z5.union([z5.literal(0), z5.literal(1)]).describe("First Bell-basis bit m1."),
    m2: z5.union([z5.literal(0), z5.literal(1)]).describe("Second Bell-basis bit m2.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ m1, m2 }) => {
    const key = `${m1}${m2}`;
    const { op, description } = OPERATORS[key];
    return {
      content: [{ type: "text", text: `Measurement ${key} \u2192 apply ${op} (${description})` }],
      structuredContent: { bits: key, operator: op, description }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "vers3dynamics-teleportation-mcp",
  title: "Vers3Dynamics Teleportation",
  version: "0.1.0",
  instructions: "Analytical quantum-mechanics tools backing the Vers3Dynamics Teleportation lab. Use `barrier_transmission` for 1D rectangular-barrier transmission (tunneling/resonant/oscillatory), `double_slit_intensity` for Fraunhofer double-slit fringes, `born_probabilities` for single-qubit measurement probabilities, `teleportation_fidelity` for Werner-state teleportation fidelity and concurrence, and `pauli_correction` to look up the Pauli operator required for a given pair of Bell-basis measurement bits.",
  tools: [
    barrier_transmission_default,
    double_slit_intensity_default,
    born_probabilities_default,
    teleportation_fidelity_default,
    pauli_correction_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
